### ISSUE TITLE
multiprocessing.pool.Remotetraceback

### ISSUE THREAD

**Issue by SirMatrix** [int-72h/ofatomic#4]
```
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/media/internald/ofatomic/ofatomic/__init__.py", line 60, in download_file_multi
    memfile = u.read()
  File "/usr/lib/python3.9/http/client.py", line 468, in read
    s = self._safe_read(self.length)
  File "/usr/lib/python3.9/http/client.py", line 609, in _safe_read
    data = self.fp.read(amt)
  File "/usr/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer
"""

The above exception was the direct cause of the following `exception:`

Traceback (most recent call last):
  File "/usr/bin/ofatomic", line 33, in <module>
    sys.exit(load_entry_point('ofatomic', 'console_scripts', 'ofatomic')())
  File "/media/internald/ofatomic/ofatomic/__init__.py", line 162, in main
    dpool.starmap(download_file_multi, todl)
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
```

**Comment by SirMatrix** [comment]
Got back from work to this error

**Comment by int-72h** [comment]
This appears to be a connection reset error which will inevitably happen so ill have to put in some exception handling

**Comment by int-72h** [comment]
b3c4232 has basic error handling but I'd like to make it actually useful. Should alleviate this error though.
